### ISSUE TITLE
Craft 3 Plans

### ISSUE THREAD

**Issue by ghost** [tippingmedia/Verses#1]
Hi there, was wondering if you have plans to update verses to be compatible with Craft 3?

**Comment by a-am** [comment]
Mike, we do have plans. We have currently been working on some of our other plugins at the moment. This will get ported over.

**Comment by ghost** [comment]
Terrific, thanks for the quick reply.

**Comment by a-am** [comment]
@mjatharvest we have done an initial port of the Verses plugin for Craft 3.  It is not in the Craft store yet however you can add it to your composer file dependancies `tippingmedia/verses`.  The plugin is not located at https://bitbucket.com/tippingmedia/verses.  We have also added support for Crossways ESV api since it is no longer available via Bibles.org service.

**Comment by ghost** [comment]
@a-am thanks for the update, I look forward to checking it out.
