### ISSUE TITLE
Uncaught TypeError: this.verses.push is not a function

### ISSUE THREAD

**Issue by johnnymueller** [tippingmedia/Verses#3]
Hello,

I've installed your plugin and can see existing verses displayed in Twig without any issues. However, when in the CP, verses aren't listed and when trying to add new ones I see the following error in the console: `Uncaught TypeError: this.verses.push is not a function at setVerse (BibleVerses.js?v=1576186022:1)`.

I've tested in Chrome and Safari with the same results.

Any ideas on what could be going on?

Thanks!
John

**Comment by a-am** [comment]
@johnnymueller the api that the Versus plugin is built on from Bibles.org has changed.  They have changed their api.  We have not ported it yet because most of the main bible version (ESV, NIV, NASB, HCSB) they offered were no longer available in the new api.  We did start a Craft 3 version here: https://bitbucket.org/tippingmedia/verses/src/master/ .  We were also trying to integrate Crossway's ESV bible api into this plugin.  It is not complete but you are welcome to try it.

**Comment by johnnymueller** [comment]
Gotcha. Thanks for the quick reply! I'll close this then and we can discuss on bitbucket if needed.
